import {readdir,readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const source=dirname(fileURLToPath(import.meta.url)),destination=resolve(process.argv[2]??'E:/deepseek-desktop/plugins/dsh-plugin-live2d-stage');
const report=resolve(source,'build/reports/live2d-plugin');await mkdir(report,{recursive:true});
const inventory=[];
async function scan(dir,prefix=''){for(const e of await readdir(dir,{withFileTypes:true})){const p=prefix+e.name;if(e.isDirectory())await scan(join(dir,e.name),p+'/');else{const bytes=await readFile(join(dir,e.name));inventory.push({path:p,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}}}
await scan(destination);
const installed={destination,bytes:inventory.reduce((n,f)=>n+f.bytes,0),files:inventory.length,inventory};
await writeFile(resolve(report,'install.json'),JSON.stringify(installed,null,2));
const browser=JSON.parse(await readFile(resolve(report,'browser-smoke.json'),'utf8'));
await writeFile(resolve(report,'dependency-increment.json'),JSON.stringify({previous:{bytes:4605678,files:52},current:{bytes:installed.bytes,files:installed.files},increment:{bytes:installed.bytes-4605678,files:installed.files-52},native:inventory.filter(x=>x.path.startsWith('lib/native/')),standalone:inventory.filter(x=>x.path.startsWith('assets/floating.')),source:JSON.parse(await readFile(resolve(source,'native/dependency.json'),'utf8')),alternatives:'Host has no native plugin window bridge; patching app.asar is invasive; shipping Electron is much larger. WPF CompositionControl reuses installed WebView2.'},null,2));
await writeFile(resolve(report,'acceptance.json'),JSON.stringify({installed:{destination,bytes:installed.bytes,files:installed.files},checks:{unitTests:11,toolbar:JSON.parse(await readFile(resolve(report,'toolbar.json'),'utf8')),sharpness:JSON.parse(await readFile(resolve(report,'sharpness.json'),'utf8')),hostSessionListCreateAndHistory:true,textButtonOpensNativeWindow:true,closeRemovesActionTools:true,actionControlToggleAndStaleToolGuard:true,nativeFloating:JSON.parse(await readFile(resolve(report,'native-floating.json'),'utf8')),installedNativeSettingsToggles:true,realModelBrowser:browser,nativeProfileBoot:true,nativeClientGraph:true,authenticatedApi:true,pluginRegistration:true},scope:{memory:false,taskPlanning:false,preview:'transparent application overlay or independent Windows topmost window',agentControl:'opt-in; at most one contextually matching, named action per user turn'},dependencies:{newNpmInstalls:0,runtime:'bundled existing unzipper, Cubism Core/Framework, React/ReactDOM for standalone page; WebView2 SDK 1.0.3537.50 Core/Wpf/Loader; system .NET Framework and installed WebView2 Runtime',development:'existing esbuild/Playwright; system csc; fixed WebView2 NuGet SDK cache; development tools and SDK cache excluded from install',alternatives:'OS ZIP extraction or handwritten ZIP parser; existing streaming library chosen'},sourceDesktopPayloadChanged:false,largeFiles:inventory.filter(x=>x.bytes>10000000),notExecuted:['restart of user desktop application','real paid Agent/model round trip','installer rollback','automatic restore after real user app restart'],notes:['Optional model vtube.json is absent in the Hiyori fixture; renderer handles its failed probe and renders successfully.','played acknowledges that the player accepted the action, not completion of the animation.','Original application bundle and frozen size baseline were not changed.']},null,2));
console.log(JSON.stringify({bytes:installed.bytes,files:installed.files,report}));
