import {Icon} from './icons';
import {useEffect,useRef,useState} from 'react';
import {api} from './api';
function ChatPanel(){
 const [sessions,setSessions]=useState<any[]>([]),[workspaces,setWorkspaces]=useState<any[]>([]),[workspace,setWorkspace]=useState(''),[session,setSession]=useState(''),[ready,setReady]=useState(false),[draft,setDraft]=useState(''),[history,setHistory]=useState<any>({messages:[]}),[error,setError]=useState(''),[sending,setSending]=useState(false);const pending=useRef<any>(null),list=useRef<HTMLDivElement>(null);
 async function refreshSessions(){const data=await api('chat/sessions');setSessions(data.items??[]);setWorkspaces(data.workspaces??[]);setReady(true);return data;}
 useEffect(()=>{let active=true;async function refresh(){try{const data=await api('chat/sessions');if(!active)return;setSessions(data.items??[]);setWorkspaces(data.workspaces??[]);setReady(true);}catch(e:any){if(active)setError(e.message);}}void refresh();const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(!ready)return;if(workspace&&!workspaces.some(w=>w.workspaceId===workspace)){setWorkspace('');setSession('');}else if(session&&!sessions.some(s=>s.sessionId===session&&(!workspace||s.workspaceId===workspace)))setSession('');},[sessions,workspaces,workspace,session,ready]);
 useEffect(()=>{setHistory({messages:[]});if(!session)return;let active=true,timer:any;async function poll(){try{const next=await api('chat/history?session='+encodeURIComponent(session));if(active)setHistory(next);}catch(e:any){if(active)setError(e.message);}finally{if(active)timer=setTimeout(poll,1000);}}void poll();return()=>{active=false;clearTimeout(timer);};},[session]);
 useEffect(()=>{if(list.current)list.current.scrollTop=list.current.scrollHeight;},[history.messages?.length]);
 async function send(){if(sending||!ready||!draft.trim()||(!session&&!workspace))return;setSending(true);setError('');if(!pending.current||pending.current.text!==draft||pending.current.sessionId!==session||(pending.current.workspaceId||'')!==workspace)pending.current={text:draft,sessionId:session,workspaceId:workspace||undefined,requestId:crypto.randomUUID(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone};try{const result=await api('chat/send',pending.current);await refreshSessions();setSession(result.sessionId);setDraft('');pending.current=null;}catch(e:any){setError(e.message);}finally{setSending(false);}}
 return <div className="l2ds-chat"><strong>Harness 文本对话</strong><select aria-label="选择工作区" value={workspace} disabled={sending||!ready} onChange={e=>{setWorkspace(e.target.value);setSession('');setError('');pending.current=null;}}><option value="">全部 Harness 会话</option>{workspaces.map(w=><option key={w.workspaceId} value={w.workspaceId}>{w.title||w.path}</option>)}</select>{workspace&&<small className="l2ds-workspace-path">{workspaces.find(w=>w.workspaceId===workspace)?.path}</small>}<select aria-label="选择对话" value={session} disabled={sending} onChange={e=>{setSession(e.target.value);setError('');}}><option value="">{workspace?'在此工作区新建对话':'请选择已有会话'}</option>{sessions.filter(s=>!workspace||s.workspaceId===workspace).map(s=><option key={s.sessionId} value={s.sessionId}>{s.title||s.sessionId}</option>)}</select>{!workspace&&!session&&<small>选择 Harness 工作区以新建对话，或选择已有会话继续。</small>}<div ref={list} className="l2ds-messages">{history.messages.map((m:any)=><div key={m.id} className={'l2ds-message '+m.role}><small>{m.role==='user'?'你':'Agent'}</small><div>{m.text}</div></div>)}{history.running&&<p>正在处理…</p>}{history.error&&<p role="alert">{history.error}</p>}</div>{error&&<p role="alert">{error}</p>}<textarea aria-label="对话内容" value={draft} maxLength={32000} onChange={e=>setDraft(e.target.value)} placeholder="输入消息，Ctrl+Enter 发送" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><button disabled={sending||!ready||!draft.trim()||(!session&&!workspace)} onClick={()=>void send()}>{sending?'发送中…':'发送'}</button></div>;
}
export function Toolbar({character,native,panel,setPanel,reset,startDrag}:{character:any;native:boolean;panel:string;setPanel:(v:string)=>void;reset:()=>void;startDrag:(e:any)=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(fn:()=>Promise<any>){setError('');setBusy(true);try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><div className="l2ds-toolbar" aria-label="人物控制"><button title="文本" aria-label="文本" disabled={busy} onClick={()=>native?setPanel(panel==='chat'?'':'chat'):void run(()=>api('chat/open',{}))}><Icon name="type"/></button><button title="动作" aria-label="动作" onClick={()=>setPanel(panel==='actions'?'':'actions')}><Icon name="face-slightly-smiling-plus"/></button><button className="l2ds-drag-handle" title="拖拽画布" aria-label="拖拽画布" onPointerDown={startDrag}><Icon name="move"/></button><button title="重置" aria-label="重置" onClick={reset}><Icon name="reload"/></button><button title={native?'移入 Harness':'移出 Harness'} aria-label={native?'移入 Harness':'移出 Harness'} disabled={busy} onClick={()=>void run(()=>api('dock',{outside:!native}))}><Icon name={native?'square-arrow-right-enter':'square-arrow-right-exit'}/></button><button title="关闭" aria-label="关闭" disabled={busy} onClick={()=>void run(()=>api('close',{}))}><Icon name="x"/></button></div>{panel&&<aside className="l2ds-sidepanel"><button className="l2ds-panel-close" aria-label="收起面板" onClick={()=>setPanel('')}>×</button>{panel==='chat'?<ChatPanel/>:<><strong>动作预览</strong><div className="l2ds-preview-actions">{character.actions.map((a:any)=><button key={a.id} disabled={busy} onClick={()=>void run(()=>api('play',{characterId:character.id,actionId:a.id}))}>{a.name}</button>)}</div></>}</aside>}{error&&<div role="alert" className="l2ds-toolbar-error">{error}</div>}</>;
}
